services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: eshop-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pg_identity_data:
  pgadmin_data:

networks:
  my_network:
    driver: bridge